### PR TITLE
Added native modifiers. Fixes jaredlll08/#4

### PR DESCRIPTION
**Pull request by dries007**
## TC Modifiers

For the modifiers to work, they need to be specified separate per 1 modifier.

Be aware that the modifiers need to be able to be allied in the game itself for this trick to work!
You cannot bypass 2 modifiers that lock each other out with this!

For example, to apply a total of 150 redstone to a tool, you have to do it in increments of 50 (the max per modifier)
Like so:
Option 1 - 3 times 5 x block (9) + 5 x dust:

``` javascript
 "nativeModifiers": [
     [
         "minecraft:redstone_block *5",
         "minecraft:redstone *5"
     ],
     [
         "minecraft:redstone_block *5",
         "minecraft:redstone *5"
     ],
     [
         "minecraft:redstone_block *5",
         "minecraft:redstone *5"
     ]
 ]
```

Option 2 - 3 times 50 redstone dust:

``` javascript
 "nativeModifiers": [
     [
         "minecraft:redstone *50"
     ],
     [
         "minecraft:redstone *50"
     ],
     [
         "minecraft:redstone *50"
     ]
 ]
```
## Enchants

Sorts the String array into an array of EnchantmentWithLevel's

The proper json formatting is a string consisting of an enchantment ID and optionally an enchantment level.
Like so: "id" or "id level".
By default a level of 1 will be assumed

In json:

``` javascript
 "nativeEnchantments": [
     "id level"
 ]
```

Or:

``` javascript
 "nativeEnchantments": [
     "id"
 ]
```

### CODE REVIEW

**Comment by jaredlll08** [comment]
Nice, may I ask why the baubles jar is there?

**Comment by dries007** [comment]
its a dependency, so added it. I also updated forge to the latest recommended.
I'm adding vanilla enchants as per request in #4.

**Comment by jaredlll08** [comment]
kk, just tell me when to merge, and it shouldn't be a dep... nothing in the mod uses it

**Comment by dries007** [comment]
its a dependency of thaumcraft I think. forge complained about it not being there when I tried starting it, so I just threw it in there :smile:

**Comment by dries007** [comment]
Done

**Pull request merged**
